image: ubuntu:20.04

before_script:
  - apt-get -y update
  - apt-get -y install gcc
  - apt-get -y install g++
  - apt-get -y install gfortran
  - apt-get -y install libgl-dev
  - apt-get -y install libglu-dev
  - apt-get -y install libglew-dev
  - apt-get -y install libocct-modeling-algorithms-dev
  - apt-get -y install libboost-dev
  - apt-get -y install cmake

build_revocap:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DWITH_EXTENSION=OFF -DWITH_OPENCASCADE=OFF ..
    - make
  artifacts:
    paths:
      - build

test_revocap:
  stage: test
  script:
    - cd build
    - make test
