def setMeshBox(mesh)
	mesh.beginModel
	mesh.beginNode(8)
	mesh.addNode(0,0,0)
	mesh.addNode(1,0,0)
	mesh.addNode(1,1,0)
	mesh.addNode(0,1,0)
	mesh.addNode(0,0,1)
	mesh.addNode(1,0,1)
	mesh.addNode(1,1,1)
	mesh.addNode(0,1,1)
	mesh.endNode
	mesh.beginElement(5)
	mesh.addElement("TETRAHEDRON",[1,5,2,0])
	mesh.addElement("TETRAHEDRON",[3,2,7,0])
	mesh.addElement("TETRAHEDRON",[4,0,7,5])
	mesh.addElement("TETRAHEDRON",[6,2,5,7])
	mesh.addElement("TETRAHEDRON",[0,2,7,5])
	mesh.endElement
	mesh.createData("test","NODEVARIABLE","SCALAR")
	mesh.setValueAtId("test",0,100.0)
	mesh.setValueAtId("test",1,101.0)
	mesh.setValueAtId("test",2,102.0)
	mesh.setValueAtId("test",3,103.0)
	mesh.setValueAtId("test",4,104.0)
	mesh.endModel
end
